# Importing required libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pickle

# Read and Cleaning the dataset

In [32]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='7AU8fQ97PZNS0Tb3z3s9faZsXvY8RxW4cPqo6rDXRmxY',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'carresalevaluepredictiondeploymen-donotdelete-pr-k7nphbfxsy2sjg'
object_key = 'Dataset.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_csv(body)
df_data_2.head()
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='7AU8fQ97PZNS0Tb3z3s9faZsXvY8RxW4cPqo6rDXRmxY',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'carresalevaluepredictiondeploymen-donotdelete-pr-k7nphbfxsy2sjg'
object_key = 'Dataset.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()

dateCrawled                            name  seller offerType  \
0  2016-03-24 11:52:17                      Golf_3_1.6  privat   Angebot   
1  2016-03-24 10:58:45            A5_Sportback_2.7_Tdi  privat   Angebot   
2  2016-03-14 12:52:21  Jeep_Grand_Cherokee_"Overland"  privat   Angebot   
3  2016-03-17 16:54:04              GOLF_4_1_4__3T�RER  privat   Angebot   
4  2016-03-31 17:25:20  Skoda_Fabia_1.4_TDI_PD_Classic  privat   Angebot   

   price abtest vehicleType  yearOfRegistration    gearbox  powerPS  model  \
0    480   test         NaN                1993    manuell        0   golf   
1  18300   test       coupe                2011    manuell      190    NaN   
2   9800   test         suv                2004  automatik      163  grand   
3   1500   test  kleinwagen                2001    manuell       75   golf   
4   3600   test  kleinwagen                2008    manuell       69  fabia   

   kilometer  monthOfRegistration fuelType       brand notRepairedDamage  \
0     150000                    0   benzin  volkswagen               NaN   
1     125000                    5   diesel        audi                ja   
2     125000                    8   diesel        jeep               NaN   
3     150000                    6   benzin  volkswagen              nein   
4      90000                    7   diesel       skoda              nein   

           dateCreated  nrOfPictures  postalCode             lastSeen  
0  2016-03-24 00:00:00             0       70435  2016-04-07 03:16:57  
1  2016-03-24 00:00:00             0       66954  2016-04-07 01:46:50  
2  2016-03-14 00:00:00             0       90480  2016-04-05 12:47:46  
3  2016-03-17 00:00:00             0       91074  2016-03-17 17:40:17  
4  2016-03-31 00:00:00             0       60437  2016-04-06 10:17:21

In [33]:
df.head()

dateCrawled                            name  seller offerType  \
0  2016-03-24 11:52:17                      Golf_3_1.6  privat   Angebot   
1  2016-03-24 10:58:45            A5_Sportback_2.7_Tdi  privat   Angebot   
2  2016-03-14 12:52:21  Jeep_Grand_Cherokee_"Overland"  privat   Angebot   
3  2016-03-17 16:54:04              GOLF_4_1_4__3T�RER  privat   Angebot   
4  2016-03-31 17:25:20  Skoda_Fabia_1.4_TDI_PD_Classic  privat   Angebot   

   price abtest vehicleType  yearOfRegistration    gearbox  powerPS  model  \
0    480   test         NaN                1993    manuell        0   golf   
1  18300   test       coupe                2011    manuell      190    NaN   
2   9800   test         suv                2004  automatik      163  grand   
3   1500   test  kleinwagen                2001    manuell       75   golf   
4   3600   test  kleinwagen                2008    manuell       69  fabia   

   kilometer  monthOfRegistration fuelType       brand notRepairedDamage  \
0     150000                    0   benzin  volkswagen               NaN   
1     125000                    5   diesel        audi                ja   
2     125000                    8   diesel        jeep               NaN   
3     150000                    6   benzin  volkswagen              nein   
4      90000                    7   diesel       skoda              nein   

           dateCreated  nrOfPictures  postalCode             lastSeen  
0  2016-03-24 00:00:00             0       70435  2016-04-07 03:16:57  
1  2016-03-24 00:00:00             0       66954  2016-04-07 01:46:50  
2  2016-03-14 00:00:00             0       90480  2016-04-05 12:47:46  
3  2016-03-17 00:00:00             0       91074  2016-03-17 17:40:17  
4  2016-03-31 00:00:00             0       60437  2016-04-06 10:17:21

In [34]:
df.shape

(371528, 20)

In [35]:
df.drop(['name', 'abtest', 'dateCrawled', 'nrOfPictures', 'lastSeen',
         'postalCode','dateCreated','offerType'], axis='columns',inplace=True)

In [36]:
df = df[(df.yearOfRegistration >= 1950) & (df.yearOfRegistration < 2017)]

In [37]:
df.shape

(356559, 12)

In [38]:
new_df = df.copy()

In [39]:
new_df = new_df.drop_duplicates ([ 'price', 'vehicleType', 'yearOfRegistration'
                                  ,'gearbox', 'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType'
                                  ,'notRepairedDamage'])

In [40]:
new_df.gearbox.replace(('manuell', 'automatik'), ('manual', 'automatic'), inplace=True)
new_df.fuelType.replace(('benzin', 'andere', 'elektro'), ('petrol', 'others', 'electric'), inplace=True)
new_df.vehicleType.replace(('kleinwagen', 'cabrio', 'kombi', 'andere'), 
                           ('small car', 'convertible', 'combination', 'others'), inplace=True)
new_df.notRepairedDamage.replace(('ja', 'nein'), ('Yes', 'No'),inplace=True)

In [41]:
new_df = new_df[(new_df.price >= 100) & (new_df.price <= 150000)]
new_df = new_df[(new_df.powerPS > 50) & (new_df.powerPS < 900)]

# Preprocessing the Data

In [42]:
new_df[ 'fuelType'].fillna(value='not-declared', inplace=True)
new_df[ 'gearbox'].fillna(value='not-declared', inplace=True)
new_df[ 'vehicleType'].fillna (value='not-declared', inplace=True)
new_df['model'].fillna(value='not-declared',inplace=True)

In [43]:
new_df.to_csv("preprocessed.csv")

In [44]:
labels = ['gearbox', 'notRepairedDamage', 'model', 'brand', 'fuelType', 'vehicleType']

In [45]:
mapper = {}
for i in labels:
    mapper[i]=LabelEncoder()
    mapper[i].fit(new_df[i])
    tr = mapper[i].transform(new_df[i])
    np.save(str('classes'+i+ '.npy'), mapper[i].classes_)
    print(i, ":",mapper[i])
    new_df.loc[:, i + '_labels'] = pd.Series (tr, index=new_df.index)

gearbox : LabelEncoder()
notRepairedDamage : LabelEncoder()
model : LabelEncoder()
brand : LabelEncoder()
fuelType : LabelEncoder()
vehicleType : LabelEncoder()


In [46]:
labeled=new_df[ ['price'
                 ,'yearOfRegistration'
                 ,'powerPS'
                 ,'kilometer'
                 ,'monthOfRegistration'
                ]
               + [x+"_labels" for x in labels]]

In [47]:
print(labeled.columns)

Index(['price', 'yearOfRegistration', 'powerPS', 'kilometer',
       'monthOfRegistration', 'gearbox_labels', 'notRepairedDamage_labels',
       'model_labels', 'brand_labels', 'fuelType_labels',
       'vehicleType_labels'],
      dtype='object')


# Splitting data into Dependent and Independent variables

In [48]:
Y = labeled.iloc[:,0].values.reshape(-1,1)
X = labeled.iloc[:,1:].values

In [49]:
print(Y)

[[18300]
 [ 9800]
 [ 1500]
 ...
 [ 9200]
 [ 3400]
 [28990]]


In [50]:
print(X)

[[  2011    190 125000 ...      1      1      3]
 [  2004    163 125000 ...     14      1      8]
 [  2001     75 150000 ...     38      7      7]
 ...
 [  1996    102 150000 ...     38      1      0]
 [  2002    100 150000 ...     38      1      1]
 [  2013    320  50000 ...      2      7      4]]


In [51]:
from sklearn.model_selection import cross_val_score, train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.4, random_state=20)

In [52]:
X_train.shape

(167146, 10)

In [53]:
X_test.shape

(111432, 10)

In [54]:
Y_train.shape

(167146, 1)

In [55]:
Y_test.shape

(111432, 1)

# Model Building

In [57]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import math

In [58]:
def find_scores(Y_actual, Y_pred, X_train):
    MSE=mean_squared_error(Y_actual,Y_pred)
    print("MSE:",MSE)
    RMSE=math.sqrt(MSE)
    print("RMSE:",RMSE)
    r2=r2_score(Y_actual,Y_pred)
    print("R2_score:",r2)
    Adjusted_R2=1-(1-r2*((X_test.shape[0]-1)/(X_test.shape[0]-X_test.shape[1]-1)))
    print("Adjusted R2:",Adjusted_R2)
#     plt.figure(figsize=(10,5))
#     plt.plot(Y_pred[0:20])
#     plt.plot(np.array(Y_test[0:20]))
#     plt.legend(["predicted","actual"])
#     plt.show()

# Choose the Appropriate Model

## Model 1 : Random Forest Regressor

In [59]:
from sklearn.ensemble import RandomForestRegressor

In [60]:
def random_forest_regressor(n_estimators,max_samples,criterion,bootstrap,random_state):
        
    model = RandomForestRegressor(
      n_estimators = n_estimators,
      criterion = criterion,
      bootstrap = bootstrap,
      max_samples = max_samples,
      random_state = random_state)
    
    model.fit(X_train, np.ravel(Y_train,order='C'))
    
    Y_pred = model.predict(X_test)
    
    find_scores(Y_test, Y_pred, X_train)

In [119]:
random_forest_regressor(100,0.3,'squared_error',True,40)

MSE: 10429809.195812337
RMSE: 3229.521511898061
R2_score: 0.8558564517160402
Adjusted R2: 0.855933264565657


In [120]:
random_forest_regressor(300,0.3,'squared_error',True,40)

MSE: 10441510.240895698
RMSE: 3231.332579741011
R2_score: 0.8556947392508089
Adjusted R2: 0.8557715375867824


In [121]:
random_forest_regressor(200,0.3,'squared_error',True,40)

MSE: 10441214.518756213
RMSE: 3231.286820874342
R2_score: 0.8556988262324297
Adjusted R2: 0.8557756249352085


In [122]:
random_forest_regressor(100,0.4,'squared_error',True,40)

MSE: 10375074.1361412
RMSE: 3221.036189821716
R2_score: 0.8566129090556145
Adjusted R2: 0.8566897897970417


In [123]:
random_forest_regressor(100,0.45,'squared_error',True,40)

MSE: 10299063.708894264
RMSE: 3209.2154351015865
R2_score: 0.8576633992883937
Adjusted R2: 0.8577403743109917


## Model 2 : Bagging Regressor

In [124]:
from sklearn.ensemble import BaggingRegressor

In [128]:
def bagging_regressor(n_estimators,bootstrap,max_samples,random_state):
    
    model = BaggingRegressor(
      n_estimators=n_estimators, 
      bootstrap=bootstrap,
      max_samples=max_samples,
      random_state=random_state)
    
    model.fit(X_train,np.ravel(Y_train,order='C'))
    
    Y_pred = model.predict(X_test)
    
    find_scores(Y_test, Y_pred, X_train)

In [129]:
bagging_regressor(100,True,0.4,40)

MSE: 10391568.470448954
RMSE: 3223.5955810940295
R2_score: 0.8563849516856314
Adjusted R2: 0.8564618119679557


In [130]:
bagging_regressor(200,True,0.4,40)

MSE: 10348619.50812465
RMSE: 3216.9270287223876
R2_score: 0.8569785211084571
Adjusted R2: 0.8570554346634519


In [131]:
bagging_regressor(300,True,0.4,40)

MSE: 10312980.19702098
RMSE: 3211.382910370699
R2_score: 0.8574710686387552
Adjusted R2: 0.8575480263997373


In [132]:
bagging_regressor(300,True,0.3,40)

MSE: 10459870.329386981
RMSE: 3234.1722788662605
R2_score: 0.8554409965166654
Adjusted R2: 0.8555177720793077


# Check the Metrics of the Model

In [61]:
model = RandomForestRegressor(
      n_estimators = 100,
      criterion = 'squared_error',
      bootstrap = True,
      max_samples = 0.45,
      random_state = 40)
    
model.fit(X_train, np.ravel(Y_train,order='C'))

RandomForestRegressor(max_samples=0.45, random_state=40)

In [62]:
Y_pred = model.predict(X_test)
find_scores(Y_test, Y_pred, X_train)

MSE: 10299063.708894264
RMSE: 3209.2154351015865
R2_score: 0.8576633992883937
Adjusted R2: 0.8577403743109917


In [63]:
!pip install ibm_watson_machine_learning

In [64]:
from ibm_watson_machine_learning import APIClient

In [65]:
wml_credentials = {
    "url": "https://us-south.ml.cloud.ibm.com",
    "apikey": "DUuV9KvAD_E4GwhrJUTSr1OuuutjS48u9YX7n9obnJPt"
}
client = APIClient(wml_credentials)

In [66]:
def guid_from_space_name(client,space_name):
    space = client.spaces.get_details()
    return (next(item for item in space['resources'] if item['entity']['name'] == space_name)['metadata']['id'])

In [67]:
space_uid = guid_from_space_name(client,'models')
print("space uid = ",space_uid)

space uid =  5e9e4d53-df3e-4916-a68f-2074d24443eb


In [68]:
client.set.default_space(space_uid)

'SUCCESS'

In [69]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [87]:
software_spec_uid = client.software_specifications.get_uid_by_name("runtime-22.1-py3.9")
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [89]:
model_details = client.repository.store_model(model=model, meta_props = {
    client.repository.ModelMetaNames.NAME: "finalModel",
    client.repository.ModelMetaNames.TYPE: "scikit-learn_1.0",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid
})
model_id = client.repository.get_model_uid(model_details)

This method is deprecated, please use get_model_id()


In [90]:
model_id

'f11bfbc4-65b0-4c7e-82b9-d5f562b610df'

In [93]:
X_train[0]

array([  2003,    116, 150000,      1,      0,      0,    204,     38,
            1,      0])

# Save the Model

In [138]:
pickle.dump(model,open('model.pkl', 'wb'))